### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by hehuang139**
### PR types

Bug fixes
### PR changes

Others
### Description

bbox 没有重置

### CODE REVIEW

**Comment by linjieccc** [comment]
@hehuang139 你好，感谢贡献代码！

麻烦签署一下[Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=3639)

**Comment by linjieccc** [comment]
@hehuang139 

002711133 seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by hehuang139** [comment]
@linjieccc 不好意思，之前的提交忘记设置local的用户配置，之前的提交是否有办法能改动？新的提交已经签署cla了

**Comment by linjieccc** [comment]
> @linjieccc 不好意思，之前的提交忘记设置local的用户配置，之前的提交是否有办法能改动？新的提交已经签署cla了

试试把之前的提交 user.email 对应的邮箱地址添加到当前github账户里

**Comment by hehuang139** [comment]
已处理

**Comment by linjieccc** [comment]
@hehuang139 感谢！

**Pull request merged**
